# Generated by Django 2.1 on 2018-06-04 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 13, 30, 38, 987128, tzinfo=utc)),
        ),
    ]
